#!/usr/bin/with-contenv fish

# create our folders
mkdir -p \
    /config/aria2 \
    /config/caddy \
    /downloads

# default config files
cp -n \
    /defaults/Caddyfile \
    /config/caddy/Caddyfile

if test ! -e /config/aria2/aria2.conf
    cp /defaults/aria2.conf /config/aria2/aria2.conf
    set secret (head -c 16 /dev/urandom | hexdump '-e"%x"')
    echo 'rpc-secret='$secret >> /config/aria2/aria2.conf
    echo "Generated new aria2 config with rpc-secret: $secret"
end

# permissions
lsiown -R abc:abc \
    /config
lsiown abc:abc \
    /downloads
